### ISSUE TITLE
Adding unit tests to modularize the visualizer

### ISSUE THREAD

**Issue by adam2392** [cronelab/ReconstructionVisualizer#8]
**Is your feature request related to a problem? Please describe.**
Right now, the entire visualizer sits inside `src/`, which makes it difficult to unit test and parse.

**Describe the solution you'd like**
With unit tests added, we can add the following to the CI config:

```
- run:
          name: Jest tests
          command: yarn coverage --maxWorkers=2
      - run:
          name: Upload to codecov
          command: yarn codecov
```

**Additional context**
See https://github.com/bids-standard/bids-validator for an example of how they do some unit testing in javascript.
